### PR TITLE
delete this

### PR DESCRIPTION
**Pull request by matmen**
in favor of #23

### CODE REVIEW

**Review by ConnorMcF — CHANGES_REQUESTED** [review]
av you got a loicense for that?

**Comment by Kefta** [comment]
Thanks for staying active on this important issue

**Review by Fogapod — APPROVED** [review]
This will literally resolve all other issues with the bot

**Comment by empt1xo** [comment]
thank you for your great work, matmen

**Comment by y21** [comment]
Bumping this, please merge

**Review by y21 — APPROVED** [review]

**Review by ozzt — APPROVED** [review]
looks good

**Comment by matmen** [comment]
@NotSoSuper any updates on this? this has been open for over a year and you haven't even replied. sad!

**Comment by ozzt** [comment]
fix

**Comment by matmen** [comment]
@NotSoSuper the original issue has been open for 2 years, 5 months and 7 days, pls fix.

**Comment by matmen** [comment]
Hey, i just saw this on my front page again, @NotSoSuper could you please fix this issue?

**Comment by matmen** [comment]
can't believe it's almost been 3 years

**Comment by Fogapod** [comment]
is repo owner even alive?

**Comment by matmen** [comment]
ah right, i think he did the not so super. too bad.

**Pull request closed without merging**
