### PR TITLE
fixing

### LINKED ISSUE #79: fix
fix

### PR DESCRIPTION
**Pull request by dm4uz3**
this fixes #79

### CODE REVIEW

**Comment by RaidAndFade** [comment]
thanks for this fix

**Comment by charagarlnad** [comment]
bruh.

**Comment by rafaelwastaken** [comment]
tested it in prod and seems to work, i recommend super approves this

**Comment by Alicegamergirl** [comment]
thanks bud. finally able to yeet my dick using the .female command

**Comment by Alicegamergirl** [comment]
nofap is notsoeasy

**Comment by charagarlnad** [comment]
D1O87ORXQAEVbMY

**Comment by charagarlnad** [comment]
f the issue

**Pull request closed without merging**
